name: Scheduled Python Script

on:
  schedule:
    - cron: '50 13 * * 1-5'  # 9:50 AM ET (13:50 UTC) Mon–Fri
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait 1 second (for 9:50:01 timing)
        run: sleep 1

      - name: Run script
        run: python orb_daily.py
